# https://travis-ci.org/

language: java
jdk: oraclejdk8

env:
    global:
        # Memory limit: 2Go
        - export JAVA_OPTS=-Xmx1g

before_install:
    # Versionning
    - mvn -B versions:display-dependency-updates
    - mvn -B versions:display-plugin-updates
    - mvn -B versions:display-property-updates

# Override: `mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V`
install: true

# Override: `mvn test -B`
script:
    - mvn -B clean deploy --settings .travis-settings.xml

# Information about failure
after_failure:
    # show memory usage again
    - sudo free -m -t
    # show actions of the OOM killer
    - sudo dmesg

# Reporting
after_success:
    # Codacy
    # Workaround: support for multi-reports
    - mkdir -p target/site/jacoco
    - curl -L "https://oss.sonatype.org/service/local/artifact/maven/redirect?g=org.jacoco&a=jacoco&e=zip&r=snapshots&v=LATEST" -o target/jacoco.zip
    - unzip -j target/jacoco.zip lib/jacococli.jar -d target
    - |
      java -jar target/jacococli.jar report \
          jsfring-common/target/jacoco.exec --classfiles jsfring-common/target/classes --sourcefiles jsfring-common/src/main/java \
          jsfring-common-test/target/jacoco.exec --classfiles jsfring-common-test/target/classes --sourcefiles jsfring-common-test\src/main/java \
          jsfring-common-security/target/jacoco.exec --classfiles jsfring-common-security/target/classes --sourcefiles jsfring-common-security\src/main/java \
          jsfring-business/target/jacoco.exec --classfiles jsfring-business/target/classes --sourcefiles jsfring-business\src/main/java \
          jsfring-batch/target/jacoco.exec --classfiles jsfring-batch/target/classes --sourcefiles jsfring-batch\src/main/java \
          jsfring-webservice/target/jacoco.exec --classfiles jsfring-webservice/target/classes --sourcefiles jsfring-webservice\src/main/java \
          jsfring-webapp-jsf/target/jacoco.exec --classfiles jsfring-webapp-jsf/target/classes --sourcefiles jsfring-webapp-jsf\src/main/java \
          --xml target/site/jacoco/jacoco.xml
    - mvn -B -N com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml

    # Heroku
    - mvn -B liquibase:update -pl jsfring-database
    - mvn -B -DskipTests clean heroku:deploy -pl jsfring-webservice
    - mvn -B -DskipTests clean heroku:deploy -pl jsfring-webapp-angularjs
    - mvn -B -DskipTests clean heroku:deploy -pl jsfring-webapp-angular
    - mvn -B -DskipTests clean heroku:deploy -pl jsfring-webapp-jsf
