# https://travis-ci.org/

language: java
jdk: oraclejdk8

env:
    global:
        # Memory limit: 2Go
        - export JAVA_OPTS=-Xmx1g

before_install:
    # Versionning
    - mvn -B versions:display-dependency-updates
    - mvn -B versions:display-plugin-updates
    - mvn -B versions:display-property-updates

# Override: `mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V`
install: true

# Override: `mvn test -B`
script:
    - mvn -B clean deploy --settings .travis-settings.xml
    # Documentation: generate site
    # Disabled: - mvn site

# Reporting
after_success:
    # Coveralls.io: publish
    - mvn coveralls:report
    # Codecov.io: publish
    - bash <(curl -s https://codecov.io/bash)

# Information about failure
after_failure:
    # show memory usage again
    - sudo free -m -t
    # show actions of the OOM killer
    - sudo dmesg

# Deploy
after_script:
    # Documentation: GitHub pages site
    # Disabled: - mvn --non-recursive com.github.github:site-maven-plugin:site

    # Heroku
    - mvn -B liquibase:update -pl jsfring-database
    - mvn -B -DskipTests heroku:deploy -pl jsfring-webservice
    - mvn -B -DskipTests heroku:deploy -pl jsfring-webapp-angularjs
    - mvn -B -DskipTests heroku:deploy -pl jsfring-webapp-angular2
    - mvn -B -DskipTests heroku:deploy -pl jsfring-webapp-jsf
